# NAME: Jordan Combitsis
# EMAIL: jcombitsis17@gmail.com
# ID: 004921527

default:
	gcc -g -o lab1b-server -Wall -Wextra -lz lab1b-server.c
	gcc -g -o lab1b-client -Wall -Wextra -lz lab1b-client.c

clean:
	rm -f lab1b-server lab1b-client lab1b-004921527.tar.gz

dist:
	tar -zcvf lab1b-004921527.tar.gz lab1b-server.c lab1b-client.c Makefile README