# NAME: Jordan Combitsis, Anchal Sinha
# EMAIL: jcombitsis17@gmail.com, anchalsinha@ucla.edu
# ID: 004921527, 204986787

default: build

build:
	cp lab3b.py lab3b
	chmod +x lab3b

clean:
	rm -f lab3b-004921527.tar.gz lab3b

dist: build
	tar -czvf lab3b-004921527.tar.gz lab3b.py Makefile README