# NAME: Jordan Combitsis
# EMAIL: jcombitsis17@gmail.com
# ID: 004921527

default: dist

clean:
	rm -f lab4a-004921527.tar.gz

dist:
	tar -zcvf lab4a-004921527.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README