# NAME: Jordan Combitsis
# EMAIL: jcombitsis17@gmail.com
# ID: 004921527

default:
	gcc -g -o lab1a -Wall -Wextra lab1a.c

clean:
	rm -f lab1a lab1a-004921527.tar.gz

dist:
	tar -zcvf lab1a-004921527.tar.gz lab1a.c Makefile README